### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by jonwright** [arcanosam/pytkogl#1]
Hello - Just to let you know that I copied your ideas and implementation to put together something working with pyopengl to support some of my old togl based code:

https://github.com/jonwright/pyopengltk

Many thanks for making this available!

**Comment by arcanosam** [comment]
Hi! sorry for my delay.

I appreciate your message and very glad to be helpful. First time here in github, I think.

Thanks for your consideration and soon I will check your work too, very curious what about you did :smile:
